local DbOption = require("Options.DbOption")

return {
  defaultVoice = DbOption.new():setValue("WIN"):combo({
    DbOption.Item(_("Windows integrated TTS")):Value("WIN"),
    DbOption.Item(_("GCloud: en-US-Standard-B")):Value("GC:en-US-Standard-B"),
    DbOption.Item(_("GCloud: en-US-Standard-C")):Value("GC:en-US-Standard-C"),
    DbOption.Item(_("GCloud: en-US-Standard-D")):Value("GC:en-US-Standard-D"),
    DbOption.Item(_("GCloud: en-US-Standard-E")):Value("GC:en-US-Standard-E"),
    DbOption.Item(_("GCloud: en-US-Wavenet-A")):Value("GC:en-US-Wavenet-A"),
    DbOption.Item(_("GCloud: en-US-Wavenet-B")):Value("GC:en-US-Wavenet-B"),
    DbOption.Item(_("GCloud: en-US-Wavenet-C")):Value("GC:en-US-Wavenet-C"),
    DbOption.Item(_("GCloud: en-US-Wavenet-D")):Value("GC:en-US-Wavenet-D"),
    DbOption.Item(_("GCloud: en-US-Wavenet-E")):Value("GC:en-US-Wavenet-E"),
    DbOption.Item(_("GCloud: en-US-Wavenet-F")):Value("GC:en-US-Wavenet-F"),
    DbOption.Item(_("AWS: Nicole")):Value("AWS:Nicole"),
    DbOption.Item(_("AWS: Russell")):Value("AWS:Russell"),
    DbOption.Item(_("AWS: Amy")):Value("AWS:Amy"),
    DbOption.Item(_("AWS: Emma")):Value("AWS:Emma"),
    DbOption.Item(_("AWS: Brian")):Value("AWS:Brian"),
    DbOption.Item(_("AWS: Aditi")):Value("AWS:Aditi"),
    DbOption.Item(_("AWS: Raveena")):Value("AWS:Raveena"),
    DbOption.Item(_("AWS: Ivy")):Value("AWS:Ivy"),
    DbOption.Item(_("AWS: Joanna")):Value("AWS:Joanna"),
    DbOption.Item(_("AWS: Kendra")):Value("AWS:Kendra"),
    DbOption.Item(_("AWS: Kimberly")):Value("AWS:Kimberly"),
    DbOption.Item(_("AWS: Salli")):Value("AWS:Salli"),
    DbOption.Item(_("AWS: Joey")):Value("AWS:Joey"),
    DbOption.Item(_("AWS: Justin")):Value("AWS:Justin"),
    DbOption.Item(_("AWS: Matthew")):Value("AWS:Matthew"),
    DbOption.Item(_("AWS: Geraint")):Value("AWS:Geraint"),
  }),
  gcloudAccessKey = DbOption.new():setValue(""):editbox(),
  awsAccessKey = DbOption.new():setValue(""):editbox(),
  awsPrivateKey = DbOption.new():setValue(""):editbox(),
  -- see https://docs.aws.amazon.com/general/latest/gr/rande.html#pol_region for regions polly is available in
  awsRegion = DbOption.new():setValue("eu-central-1"):combo({
    DbOption.Item(_("ap-northeast-1")):Value("ap-northeast-1"),
    DbOption.Item(_("ap-northeast-2")):Value("ap-northeast-2"),
    DbOption.Item(_("ap-south-1")):Value("ap-south-1"),
    DbOption.Item(_("ap-southeast-1")):Value("ap-southeast-1"),
    DbOption.Item(_("ap-southeast-2")):Value("ap-southeast-2"),
    DbOption.Item(_("ca-central-1")):Value("ca-central-1"),
    DbOption.Item(_("cn-northwest-1")):Value("cn-northwest-1"),
    DbOption.Item(_("eu-central-1")):Value("eu-central-1"),
    DbOption.Item(_("eu-north-1")):Value("eu-north-1"),
    DbOption.Item(_("eu-west-1")):Value("eu-west-1"),
    DbOption.Item(_("eu-west-2")):Value("eu-west-2"),
    DbOption.Item(_("eu-west-3")):Value("eu-west-3"),
    DbOption.Item(_("sa-east-1")):Value("sa-east-1"),
    DbOption.Item(_("us-east-1")):Value("us-east-1"),
    DbOption.Item(_("us-east-2")):Value("us-east-2"),
    DbOption.Item(_("us-gov-west-1")):Value("us-gov-west-1"),
    DbOption.Item(_("us-west-1")):Value("us-west-1"),
    DbOption.Item(_("us-west-2")):Value("us-west-2"),
  }),
  srsPort = DbOption.new():setValue("5002"):editbox(),
  debugLoggingEnabled = DbOption.new():setValue(false):checkbox()
}
